### ISSUE TITLE
confuse about results from Mask-rcnn

### ISSUE THREAD

**Issue by qinhaifangpku** [RanTaimu/M-CE2P#1]
HI, Thanks for your great work.

I wonder if you can share your mask-rcnn configuration like backbone or even the trained weights?

Thank you in advance!

**Comment by RanTaimu** [comment]
@qinhaifangpku Just use the script named "infer_simple.py" in "tools" folder, everything is in a default manner:
```shell
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
```
More specifically, you should modify the "vis_utils.vis_one_image()" method to return the boxes, masks that used in M-CE2P, like following:

```python
# Code in tools/infer_simple.py
boxes, masks, classes = vis_utils.vis_one_image(
            im[:, :, ::-1],  # BGR -> RGB for visualization
            im_name,
            args.output_dir,
            cls_boxes,
            cls_segms,
            cls_keyps,
            dataset=dummy_coco_dataset,
            box_alpha=0.3,
            show_class=True,
            thresh=0.7,
            kp_thresh=2,
            visualize=visualize
        )
```

```python
# Code in detectron/utils/vis.py
def vis_one_image(
        im, im_name, output_dir, boxes, segms=None, keypoints=None, thresh=0.9,
        kp_thresh=2, dpi=200, box_alpha=0.0, dataset=None, show_class=False,
        ext='pdf', visualize=True):
    """Visual debugging of detections."""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    if isinstance(boxes, list):
        boxes, segms, keypoints, classes = convert_from_cls_format(
            boxes, segms, keypoints)

    # There are five value to represent a
    # box: [x1, y1, x2, y2, score]
    if boxes is None or boxes.shape[0] == 0 or max(boxes[:, 4]) < thresh:
        return None, None, None

    dataset_keypoints, _ = keypoint_utils.get_keypoints()
    # masks: [height, width, num_obj]
    # For every object mask [:, :, i], it's a binary mask
    # (0 for background and 1 for foreground).
    if segms is not None and len(segms) > 0:
        masks = mask_util.decode(segms)

    if not visualize:
        return boxes, masks, classes

    # ..............
```

**Comment by LayneH** [comment]
@RanTaimu Hi, did you use threshold for bbox area (i.e. filter out small ROIs)?
I've tried to extract bbox for val set of CIHP dataset with default setting, but it turns out that I got different bbox output to you. 
Could you provide more details of this procedure? Thanks a lot.

**Comment by RanTaimu** [comment]
@LayneH  I apologize for the delay in updating the related code. Please check **get_objs()** function in **MHP_infer_simple_test.py** for details. I do have filtered out some bbox.

**Comment by LayneH** [comment]
@RanTaimu Thanks again for sharing your code!
BTW, it seems that the loss drop slowly when training B_l1 or B_l2 (stuck in around 1.3 in my case). Did you come across such situation?

**Comment by RanTaimu** [comment]
@LayneH For training details, you can make an issue in [CE2P](https://github.com/liutinglt/CE2P)

**Comment by aishoushi** [comment]
Hi, when I use infer_simple.py, it turns out such problem:
I/O Error: Couldn't open file 'infer_outputs/*.pdf': No such file or directory.
Syntax Error: Could not merge damaged documents ('infer_outputs/*.pdf')
why is it?

**Comment by TuanHAnhVN** [comment]
@RanTaimu when i run code for generating boxes and masks from mask r-cnn, my Pc didn't generate anything. After above 10 hour, always show the following pic:
![Screenshot from 2019-03-16 07-59-53](https://user-images.githubusercontent.com/19376164/54468680-bb692080-47c1-11e9-9689-37533b786976.png)

My Laptop: core i7 8th, Ram 8GB, 1050Ti

**Comment by RanTaimu** [comment]
@hoanganhtuanfsoft  Did you return the boxes and segs ahead of time at which shown in  https://github.com/RanTaimu/M-CE2P/issues/1#issuecomment-429206174 ? We needn't output the visualized results.

**Comment by aishoushi** [comment]
Thanks for your reply, I have resolved this problem, the reason is my data label  was wrong.
----- 原始邮件 -----
发件人: "RanTaimu" <notifications@github.com>
收件人: "RanTaimu/M-CE2P" <M-CE2P@noreply.github.com>
抄送: "aishoushi" <liqiangao@sjtu.edu.cn>, "Comment" <comment@noreply.github.com>
发送时间: 星期一, 2019年 3 月 18日 下午 8:09:12
主题: Re: [RanTaimu/M-CE2P] confuse about results from Mask-rcnn (#1)

Did you return the boxes and segs ahead of time at which shown in  https://github.com/RanTaimu/M-CE2P/issues/1#issuecomment-429206174 ? We needn't output the visualized results.

**Comment by hoanganhtuanfsoft** [comment]
@RanTaimu  Should I use use the script named "infer_simple.py" in "tools" folder or your script named "MHP_infer_simple_train.py" in "code_for_maskrcnn" folder?
