### ISSUE TITLE
Cannot download from Baidu Drive

### ISSUE THREAD

**Issue by lcybuzz** [RanTaimu/M-CE2P#2]
Hi~ @RanTaimu Thank you sharing models and codes. Would you please offer a Google Drive download link? Baidu Drive is not available in my place.
P.S. I tried to retrain the CE2P model on CIHP dataset with randomly initialized layer6 and layer7. But after 20 epochs, the loss still failed to converge. Have you met this problem before? Thanks!

**Comment by RanTaimu** [comment]
@lcybuzz The download link will be updated soon(The uploading process is very very slow here ...). For training details, you can open an issue in [CE2P](https://github.com/liutinglt/CE2P) repository.

**Comment by RanTaimu** [comment]
@lcybuzz I've updated the link [Google Drive](https://drive.google.com/open?id=1RF0UN-Csoyc7mkt9txVPKouzKZ2AZol9)

**Comment by lcybuzz** [comment]
Thanks!
