### ISSUE TITLE
How to run M-CE2P-test.py on GPU

### ISSUE THREAD

**Issue by TuanHAnhVN** [RanTaimu/M-CE2P#3]
Dear RanTaimu,
I can not run this file on GPU. When running, only CPU core was used with an input. Ram (16GB) was full. I also change global_model.cuda() to global_model.cuda(0), gt_model.cuda() to gt_model.cuda(0), mrcnn_model.cuda() to mrcnn_model.cuda(0). and then set dataloader with num_workers = 4.
But when i saw monitor, only cpu core was used and my gpu was not used.

I run on MHP v.2
Help me!

**Comment by RanTaimu** [comment]
[This line](https://github.com/RanTaimu/M-CE2P/blob/c643cdd41ec564d5a1a290f2752e03bdaaeadd82/M-CE2P-test.py#L542) specify the GPUs that you will use in the program. Please confirm that your pytorch is a cuda-compiled version and can utilize GPU normally. You can use 'torch.cuda.is_available()' to check that.
