### ISSUE TITLE
Can not train/evaluate M-CE2P 

### ISSUE THREAD

**Issue by TuanHAnhVN** [RanTaimu/M-CE2P#4]
Hey friends,
I can not train or evaluate M-CE2P.
For evaluating, i also downloaded weights. But i think the current source doesnt support for MHPv2.0 (for only LIP CE2P). I also change dataset to dataset_for_mhp. Many information is lose as label 

Can you show me or point me how to train/evaluate your source?
Thank you so much!

**Comment by RanTaimu** [comment]
You can refer to the training process of CE2P to perform an analogous way for training on the multiple person datasets like MHP v2. Recently we updated the data generation process in CE2P repo, so that you can acquire necessary label files in an automated manner.
