### ISSUE TITLE
The image_dir for evaluation

### ISSUE THREAD

**Issue by Xxxia96** [RanTaimu/M-CE2P#6]
i want to ask when i try to test the results on the CHIP datasets, why the image_dir path is contained the image for VOC datasets in your M-CE2P-test.py. And when i download the weight for inference,the list file should choose the testlist?  the list point to which dataset? LIP or CHIP?

**Comment by RanTaimu** [comment]
@xuxixia We didn't use VOC to perform our experiments, maybe it's a piece of useless code. You should use CIHP, rather than LIP.

**Comment by Xxxia96** [comment]
你好，请问您这个代码如果训练的话，一般几块GPU能跑起来呢？我目前用了两块但是一直都是out of memory.
还有您好像是我们六楼的师兄，能留一下邮箱吗？有问题我还想请教一下！很感谢！

**Comment by RanTaimu** [comment]
Very sorry for the late reply... you can contact me by rantaimu@bjtu.edu.cn
