### ISSUE TITLE
detectron

### ISSUE THREAD

**Issue by YOKE** [RanTaimu/M-CE2P#7]
Thanks for your great work!
I'd like to rerun this work first, but I can't install caffe2 for detectron (have tried many tutorials ...), could you help me? Thanks a lot! @RanTaimu 
environment:
cuda9.0
cudnn7
python3.6.9
pytorch0.3.1

**Comment by RanTaimu** [comment]
@YOKE I feel really sorry for the late reply... There are lots of great detection frameworks, such as mmdetection and maskrcnn-benchmark, that implemented by pure PyTorch. I think you can try them :)
