### ISSUE TITLE
Box map about  Maskrcnn on LV-MHP-v2 val 

### ISSUE THREAD

**Issue by zrl4836** [RanTaimu/M-CE2P#8]
Hello,do you have a result that Box Map about  Maskrcnn on LV-MHP-v2 val ?

**Comment by RanTaimu** [comment]
@zrl4836 I didn't preserve the box information. But now you can use mmdetection, maskrcnn-benchmark, etc. to generate the boxes. It's ok to just use the pretrained model of a mask-rcnn architecture.

**Comment by zrl4836** [comment]
OK，thank you.
