### ISSUE TITLE
about the result in CIHP val set.

### ISSUE THREAD

**Issue by zrl4836** [RanTaimu/M-CE2P#9]
Hello.Can you tell me the result on the  CIHP val set. The paper [BraidNet](https://www.researchgate.net/publication/334535123_BraidNet_Braiding_Semantics_and_Details_for_Accurate_Human_Parsing?enrichId=rgreq-fd4a5ca8b6b182a9d80bb907fc24dd52-XXX&enrichSource=Y292ZXJQYWdlOzMzNDUzNTEyMztBUzo4MDAwMjA0ODM4MDEwODhAMTU2Nzc1MTE1NTk0MQ%3D%3D&el=1_x_3&_esc=publicationCoverPdf)say your model mIOU 59.50 and APm 42.83. But I test your model mIOU 60.74 and APm 44.48 without flip and mIOU 60.94 and APm 44.76 with flip.I want to check wether  I have some error when testing.
Thanks.

**Comment by RanTaimu** [comment]
@zrl4836 According to the recorded results, Our model($B_g$ + $B_{l_1}$ + $B_{l_2}$) achieves 63.59 in terms of mIOU with label refinement, 48.92 in terms of Mean $AP^r$ with label refinement. Without label refinement, we achieve 63.59 on mIOU and 45.31 on Mean $AP^r$, respectively.

For single model B_g with label refinement, we achieve 60.45 on mIoU, 42.40 on mean AP^r, w/o flip.
